### ISSUE TITLE
Activating plugin breaks WP-CLI

### ISSUE THREAD

**Issue by morganestes** [mAAdhaTTah/WP-Gistpen#25] opened 2015-01-20 20:54 UTC
After activating the plugin via the Admin UI (see #23), I can no longer use WP-CLI commands without getting a fatal error:

```
$ wp plugin list
Fatal error: Call to undefined method Composer\Autoload\ClassLoader::setPsr4() in /home/morgan50/public_html/wp-content/plugins/wp-gistpen.tmp/lib/composer/autoload_real.php on line 37
```

**Comment by mAAdhaTTah** [comment] 2015-01-20 21:05
Errrgh, I guess that build was broken. I have to clean up the build process, now is as good a time as any :/. If you have composer, gulp, and bower on whatever system you're running this on, you can download the source and run `npm install` and `gulp init` (which runs `bower install` and `composer install` for you) to get everything working.

Otherwise, I'll fix the build process tonight and upload a new version.

**Comment by morganestes** [comment] 2015-01-20 21:13
I've only tried it on my main site, which is on shared hosting and doesn't have access to much beyond wp-cli. I'll install it on my dev site and take a look there, too.

**Comment by mAAdhaTTah** [comment] 2015-01-21 04:06
This looks like it's a WP-CLI issue: https://github.com/wp-cli/wp-cli/issues/1235 - I pinged them to reopen the ticket, but I'm not able to reproduce it. What version of WP-CLI are you running? I've got 0.15.0 and no issue.

**Comment by mAAdhaTTah** [comment] 2015-01-21 04:24
This might also be fixed by https://github.com/mAAdhaTTah/WP-Gistpen/releases/tag/0.5.0b2, but I'm not sure. Let me know what you find.

**Comment by mAAdhaTTah** [comment] 2015-01-21 17:37
It might not, actually. The conflict wasn't with the composer.json but with the autoloader, so I don't know if that'll help.

**Comment by mAAdhaTTah** [comment] 2015-02-08 02:02
Can you share `wp --info`?

**Comment by mAAdhaTTah** [comment] 2015-02-08 21:51
@morganestes If you're still experiencing this in beta2, let me know. I'm planning to release this to .org next week; hoping to clobber any bugs before then.

**Comment by danielbachhuber** [comment] 2015-09-20 14:51
@mAAdhaTTah Did you get this sorted out?

**Comment by mAAdhaTTah** [comment] 2015-09-20 18:04
@danielbachhuber I was never able to reproduce it, so if @morganestes is no longer experiencing it, then it's sorted, I guess.

**Comment by mAAdhaTTah** [comment] 2015-09-21 17:30
Closing this ticket, since the matching wp-cli ticket is closed. If you can reproduce, feel free to reopen.

**Closed by mAAdhaTTah** 2015-09-21 17:30 UTC
